### ISSUE TITLE
Designing New Layout for the App.

### ISSUE THREAD

**Issue by hmtj99** [hmtj99/PollKaro#2]
A new intuitive layout design is required for the app. The layouts can be designed on paper, photoshop, Figma or any other tool of your choice. This issue doesn't need any coding done.

**Comment by bhaveshlohana** [comment]
Assign this issue to me.

**Comment by hmtj99** [comment]
I have assigned this issue to you.

**Comment by hmtj99** [comment]
@bhaveshlohana....Make a separate folder in your forked repo for all the design files(It should contain the screenshots and all the Figma files for the design of the app), Once we finalize the design we will merge the folder into the main repo.

**Comment by bhaveshlohana** [comment]
Okay, I'll do it.

**Comment by hmtj99** [comment]
:+1:
