### ISSUE TITLE
Organize the Web App files into a single folder.

### ISSUE THREAD

**Issue by hmtj99** [hmtj99/PollKaro#9]
Make a separate folder for the web app part and also organize all the CSS and Javascript files separately.

**Comment by mnraza-dev** [comment]
I would like to work on this issue. May I?

**Comment by hmtj99** [comment]
I am sorry but this project is part of the Semester Long Projects Event organized by DSC-DAIICT, Only selected members are allowed to work on the issues.

**Comment by bhaveshlohana** [comment]
I'll do it.

**Comment by hmtj99** [comment]
I am assigning the issue to you.
